- hosts: prometheus
  roles:
    - cloudalchemy.prometheus
  vars:
    prometheus_config_global:
      scrape_interval: '15s'
      evaluation_interval: '15s'
    prometheus_alerting_alertmanagers:
      - static_configs:
          - targets: ['alertmanager:9093']
    prometheus_scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: '5s'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'node'
        scrape_interval: '15s'
        static_configs:
          - targets: ['node-exporter:9100']
      - job_name: 'mongodb'
        scrape_interval: '30s'
        static_configs:
          - targets: ['mongodb-exporter:9216']