- hosts: all
  roles:
    - role: firewall
      vars:
        firewall_allowed_tcp_ports:
          - 80
          - 443
        firewall_allowed_udp_ports: []
        firewall_allowed_icmp_types: []
        firewall_default: deny